# Generated by Django 6.0.4 on 2026-04-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_group_join_code_group_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='join_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
