# Generated by Django 6.0.4 on 2026-04-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teamrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamrating',
            name='rating',
        ),
        migrations.AddField(
            model_name='teamrating',
            name='collaboration',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='teamrating',
            name='communication',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='teamrating',
            name='contribution',
            field=models.IntegerField(default=5),
        ),
    ]
