# Generated by Django 6.0.4 on 2026-04-20 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_teamrating_rating_teamrating_collaboration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='project_submissions/')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_submissions', to='core.group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_submissions', to='core.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_project_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
